repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        description: 'Runs linter'
        entry: bash -c 'uv run make lint'
        language: system
        pass_filenames: false
      