repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        description: 'Runs linter'
        entry: bash -c 'make lint'
        language: system

      - id: test
        name: test
        description: 'Runs tests'
        entry: bash -c 'make test'
        language: system